### ISSUE TITLE
Unable to connect to charmader9

### ISSUE THREAD

**Issue by LooterToGo** [PixelmonToGo/k8s-gitops#10] opened 2021-05-29 20:36 UTC
Everyone keeps getting 
![image](https://user-images.githubusercontent.com/56703279/120084153-49ddca00-c0ce-11eb-8ed1-b02f3d7e32bf.png)

**Comment by ChipWolf** [comment] 2021-06-01 19:53
Duplicate of #8

**Closed by ChipWolf** 2021-06-01 19:53 UTC
